StartupEvents.registry("block", event => {
    event.create("curlamoety:blackmage_souls_statue_1", "animatable")
    .box(1, 0, 1, 15, 40, 15, true)
    .defaultGeoModel()
    .stoneSoundType()
    .tagBlock('minecraft:mineable/pickaxe')

    event.create("curlamoety:blackmage_souls_statue_2", "animatable")
    .box(1, 0, 1, 15, 40, 15, true)
    .defaultGeoModel()
    .stoneSoundType()
    .tagBlock('minecraft:mineable/pickaxe')

    event.create("curlamoety:witch_desk","cardinal")
    .hardness(1)
    .box(1, 0, 1, 15, 12, 15,true)
    .renderType("translucent")
    .defaultCutout()
    .tagBlock('minecraft:mineable/axe')

    event.create("curlamoety:perfect_matter","basic")
    .box(0, 0, 0, 16, 16, 16,true)
    .hardness(42)
    .stoneSoundType()
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_diamond_tool')
    .tagBlock('cataclysm:netherite_monstrosity_immune')
    .tagBlock('cataclysm:harbinger_immune')
    .tagBlock('minecraft:wither_immune')
    .tagBlock('minecraft:dragon_immune')
    .tagBlock('cataclysm:ignis_immune')
    .tagBlock('cataclysm:maledictus_immune')
    .tagBlock('cataclysm:scylla_immune')
    .tagBlock('cataclysm:leviathan_immune')
    .tagBlock('cataclysm:altar_destroy_immune')
    .tagBlock('cataclysm:remnant_immune')
    .tagBlock('cataclysm:clawdian_immune')
    .tagBlock('twilightforest:carminite_reactor_immune')
    .tagBlock('twilightforest:common_protections')

    event.create("curlamoety:calamitas_plushie","cardinal")
    .hardness(1)
    .box(5, 0, 5, 11, 10, 11,true)
    .renderType("cutout")
    .soundType("wool")
    .defaultCutout()

    event.create("curlamoety:calamitas_plushie_maid","cardinal")
    .hardness(1)
    .box(5, 0, 5, 11, 10, 11,true)
    .renderType("cutout")
    .soundType("wool")
    .defaultCutout()

    event.create("curlamoety:daochan_plushie","cardinal")
    .hardness(1)
    .box(5, 0, 5, 11, 10, 11,true)
    .renderType("cutout")
    .soundType("wool")
    .defaultCutout()

})