
#世界初始化设置
#World Initialization Settings
[world_init]
	# 是否启用首次加载存档初始化逻辑。
	#Enable first world-load initialization logic.
	enable = true
	# 首次加载这个存档时执行的指令列表。每个列表项或每一行都会被当作一条独立指令执行。不要加斜杠 /，如果误加也会自动去掉。某条指令失败不会阻止后续指令继续执行，失败内容会提醒在线管理员。
	#示例:
	#["say World Initialized!", "gamerule keepInventory true", "time set day"]
	#
	#Command list executed only on the first load of this world. Each list entry or each line is treated as one independent command. Do not add slash /. If slash is added by mistake, it will be removed automatically. A failed command will not stop later commands, and online admins will be notified.
	#Examples:
	#["say World Initialized!", "gamerule keepInventory true", "time set day"]
	commands = []

